# Generated by Django 4.0.4 on 2023-01-08 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='username',
            field=models.TextField(default='userTEST'),
        ),
    ]
